from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pymongo import MongoClient
from bson import ObjectId
from pydantic import BaseModel
from fastapi.responses import FileResponse
from fpdf import FPDF
from dotenv import load_dotenv
import tempfile
import os
import time
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from bson import ObjectId
from io import BytesIO
from xhtml2pdf import pisa

load_dotenv()

# --- MongoDB Setup ---
MONGO_URI = os.getenv("MONGO_URI")
client = MongoClient(MONGO_URI)
db = client["email_automation"]
emails_collection = db["emails"]

# --- FastAPI Setup ---
app = FastAPI(title="Contract RAG API")

# Enable frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Pydantic Models ---
class DocumentIn(BaseModel):
    title: str
    content: str
    status: str = "draft"

# --- Serializer ---
def serialize_doc(doc):
    """Convert a MongoDB document into a frontend-friendly format."""
    return {
        "id": str(doc["_id"]),
        "title": doc.get("subject") or doc.get("title") or "Untitled Document",
        "content": doc.get("contract_data") or doc.get("content") or "",
        "status": doc.get("status", "draft"),
        "timestamp": doc.get("timestamp", time.time()),
        "sender": doc.get("sender", ""),
        "threadId": doc.get("threadId", ""),
    }

# --- API Routes ---
@app.get("/documents/")
def get_all_documents():
    """Return all contract drafts generated by RAG."""
    docs = list(emails_collection.find({"contract_data": {"$exists": True}}))
    return [serialize_doc(d) for d in docs]

@app.get("/documents/{doc_id}")
def get_document(doc_id: str):
    """Fetch a single contract by ID."""
    doc = emails_collection.find_one({"_id": ObjectId(doc_id)})
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")
    return serialize_doc(doc)

@app.post("/documents/")
def create_document(doc: DocumentIn):
    """Create a new document manually (optional)."""
    record = {
        "subject": doc.title,
        "contract_data": doc.content,
        "status": doc.status,
        "timestamp": time.time(),
    }
    res = emails_collection.insert_one(record)
    return {"id": str(res.inserted_id)}

# @app.put("/documents/{doc_id}")
# def update_document(doc_id: str, data: dict):
#     """Update the document (content or status)."""
#     result = emails_collection.update_one(
#         {"_id": ObjectId(doc_id)}, {"$set": data}
#     )
#     if result.matched_count == 0:
#         raise HTTPException(status_code=404, detail="Document not found")
#     return {"message": "Document updated successfully"}

@app.put("/documents/{doc_id}")
def update_document(doc_id: str, data: dict):
    """Update the document (content or status)."""
    update_data = data.copy()

    # ✅ Keep contract_data in sync with content (important!)
    if "content" in update_data:
        update_data["contract_data"] = update_data["content"]

    result = emails_collection.update_one(
        {"_id": ObjectId(doc_id)},
        {"$set": update_data}
    )
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="Document not found")
    return {"message": "Document updated successfully"}


from fastapi.responses import StreamingResponse
from io import BytesIO
from xhtml2pdf import pisa

@app.get("/documents/{doc_id}/export")
def export_document(doc_id: str):
    """Export a document as a well-formatted PDF using xhtml2pdf."""
    try:
        document = emails_collection.find_one({"_id": ObjectId(doc_id)})
    except:
        raise HTTPException(status_code=400, detail="Invalid document ID")

    if not document:
        raise HTTPException(status_code=404, detail="Document not found")

    html_content = document.get("contract_data") or document.get("content", "")
    title = document.get("subject") or document.get("title") or "Document"

    if not html_content.strip():
        raise HTTPException(status_code=400, detail="Document has no content to export")

    # 🧾 Inject clean default styles for xhtml2pdf
    styled_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            @page {{
                size: A4;
                margin: 1.2in 0.9in 1.2in 0.9in;
            }}
            body {{
                font-family: Helvetica, Arial, sans-serif;
                font-size: 11pt;
                color: #222;
                line-height: 1.5;
            }}
            h1, h2, h3 {{
                color: #0a0a0a;
                text-align: center;
                margin-bottom: 10px;
            }}
            h1 {{ font-size: 20pt; }}
            h2 {{ font-size: 16pt; }}
            h3 {{ font-size: 14pt; }}
            p {{
                text-align: justify;
                margin: 8px 0;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin: 15px 0;
            }}
            th, td {{
                border: 1px solid #aaa;
                padding: 6px 8px;
                text-align: left;
            }}
            th {{
                background-color: #f2f2f2;
                font-weight: bold;
            }}
            .footer {{
                position: fixed;
                bottom: -20px;
                left: 0;
                right: 0;
                text-align: center;
                font-size: 9pt;
                color: #666;
            }}
            .header {{
                position: fixed;
                top: -40px;
                left: 0;
                right: 0;
                text-align: center;
                font-size: 10pt;
                color: #999;
            }}
            .page-break {{
                page-break-before: always;
            }}
        </style>
    </head>
    <body>
        <div class="header">Generated by Contract Automation System</div>

        {html_content}

        <div class="footer">
            Page <pdf:pagenumber /> of <pdf:pagecount />
        </div>
    </body>
    </html>
    """

    # 🧩 Convert to PDF
    pdf_buffer = BytesIO()
    pisa_status = pisa.CreatePDF(
        src=styled_html,
        dest=pdf_buffer,
        encoding="utf-8"
    )

    if pisa_status.err:
        raise HTTPException(status_code=500, detail="PDF generation failed")

    pdf_buffer.seek(0)
    filename = f"{title.replace(' ', '_')}.pdf"

    return StreamingResponse(
        pdf_buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
